language: node_js
node_js: 6
dist: trusty
sudo: required
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  yarn: true
  directories:
  - node_modules
  - bower_components
  - bower_components-1.x
  - .eslintcache
  - $HOME/.cache/bower
before_script:
- yarn run lint
script:
- xvfb-run yarn test
notifications:
  slack:
    secure: Ijq6DWrCfSGCDv6a5OgzpcNNFNJDtOkBel67AzizrSYEPGExe6YVp9Hp41ln8BGMgO3KNguM11SAWsEy9r8slCE9rcWeYVlIRxQo+0Tvggahz9oCNqh10Mn+0qtg+YKILv4ZnYgLuk0nm3ua2eOV7ypOjXboZ+CYjes4VjwbRbuSO9JT3oui9Kzz/ZXl/TeFwITbMgVQR3Y37O4OxBaXCQGRbkNdI9JfOwl1UmGDqC4i4KLBa2ZKXv4CxH70qxUvEBHpmsCbYOrk2Fj0Njrp5L2Fzs73fy4sKAnfUE9UxRRXTrgfoobBBH+Xw31sU/PZu+R+KPZaWjg9EHEDV6DDyhfAbn5lFbAWoCtgplVsukQP5CxDTugr1fmTxduaxhfaaGyQyAAo7OoexwrlzqCRuLocDRUMNSenxzMuQZe2GAx24MG5HZmCWhz834qrOGONTxUkn8bdI6x/g3xML1BGPzOTdZz/89rF5PDinqoZGJmslpXDc/yH/h//As+9Mbh98+08HFNYoQrdPTL1CqhtYKeUjkijk7CgCUztdLN6RqfbEMfdlxcR7lKQH5r0W5N1nw36qZ+iiL8HlIeG26/wrGX31oi2syo/jV294G6+3YMgqghSXS6hInJ8+GuiQEN4pDvXfK8QqLGxNTTaxdn5GkRvlTuZzuOJZLUhnPtCt+o=
